[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "cp .env.railway .env",
    "php artisan config:cache",
    "php artisan route:cache", 
    "php artisan view:cache",
    "chmod -R 755 storage",
    "chmod -R 755 bootstrap/cache",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh"
