[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.gd']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --ignore-platform-reqs'
]

[phases.start]
cmd = 'php artisan config:cache && php artisan migrate --force && php -S 0.0.0.0:$PORT router.php'

[variables]
APP_URL = "https://c2c-ecommerce-laravel-production-7647.up.railway.app"
